version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: telemetry
    volumes:
      - ${TIMESCALE_DATA}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana
    ports:
      - "3000:3000"
